site_name: メジャーメントラボ 

theme:
  name: material
  features:
    - navigation.tabs

    - toc.integrate
  language: ja

#extra:
#  analytics:
#    provider: google
#    property: G-HMS51W1X76

plugins:
  - search:
      lang: ja
